"use client";

import { Lock, Shield } from "lucide-react";

export const TermsContent = () => (
    <div className="prose prose-slate dark:prose-invert max-w-none">
        <h3>1. Introduction</h3>
        <p>
            Welcome to Inkless ("we," "our," or "us"). By accessing or using our platform, you agree to be bound by these Terms of Service.
            Inkless provides a secure, zero-upload digital signature platform powered by post-quantum cryptography.
        </p>

        <h3>2. User Responsibilities</h3>
        <p>
            You are responsible for maintaining the confidentiality of your account credentials and private keys.
            Since Inkless uses a non-custodial key management system (your keys are stored on your device), <strong>we cannot recover lost private keys</strong>.
        </p>
        <ul className="list-disc pl-5 space-y-2">
            <li>You agree to use this service only for lawful purposes.</li>
            <li>You will not attempt to reverse engineer the cryptographic engine.</li>
            <li>You acknowledge that signatures generated on your device are legally binding under the Nigerian Evidence Act (2011).</li>
        </ul>

        <h3>3. Service Limitations</h3>
        <p>
            Inkless provides the technological framework for digital signing. We do not validate the legal content of your documents.
            We enable the proof of integrity and authenticity, but the legal validity of the agreement itself depends on the content and jurisdiction.
        </p>

        <h3>4. Intellectual Property</h3>
        <p>
            All intellectual property rights in the platform, including the Wasm hashing engine and interface designs, belong to Inkless.
        </p>

        <h3>5. Disclaimer of Warranties</h3>
        <p>
            The service is provided "as is" without warranties of any kind. We do not guarantee that the service will be uninterrupted or error-free.
        </p>

        <h3>6. Modifications</h3>
        <p>
            We reserve the right to modify these terms at any time. Continued use of the platform constitutes agreement to the updated terms.
        </p>
    </div>
);

export const PrivacyContent = () => (
    <div className="prose prose-slate dark:prose-invert max-w-none">
        <div className="p-4 rounded-xl bg-blue-500/5 border border-blue-500/10 mb-6">
            <h4 className="flex items-center gap-2 text-blue-600 dark:text-blue-400 font-semibold m-0 mb-2">
                <Lock className="h-4 w-4" />
                Zero-Knowledge Guarantee
            </h4>
            <p className="text-sm m-0">
                Inkless is built on the principle of **Zero-Knowledge Privacy**. We <strong>never</strong> see or store your documents. All hashing happens locally on your device.
            </p>
        </div>

        <h3>1. Data Collection</h3>
        <p>We collect minimal information necessary to provide our service:</p>
        <ul className="list-disc pl-5 space-y-2">
            <li><strong>Identity Information:</strong> Name, Email, and NIN Virtual Token (when verified via NIMC).</li>
            <li><strong>Device Information:</strong> Public keys generated by your device's Secure Enclave/TPM.</li>
            <li><strong>Usage Data:</strong> Transaction metadata (time, document hash) logged on the ledger.</li>
        </ul>

        <h3>2. How We Use Your Data</h3>
        <p>Your data is used solely for:</p>
        <ul className="list-disc pl-5 space-y-2">
            <li>Authenticating your identity during signing sessions.</li>
            <li>Creating immutable audit trails on the blockchain.</li>
            <li>Preventing fraud and ensuring non-repudiation.</li>
        </ul>

        <h3>3. Security Architecture</h3>
        <p>
            We utilize <strong>Crystals-Dilithium (ML-DSA)</strong>, a NIST-standardized post-quantum cryptographic scheme.
        </p>
        <ul className="list-disc pl-5 space-y-2">
            <li><strong>No Document Uploads:</strong> Only cryptographic hashes are transmitted.</li>
            <li><strong>Hardware-Bound Keys:</strong> Private keys never leave your device.</li>
            <li><strong>Audit Trails:</strong> Every transaction is anchored to an immutable ledger for legal non-repudiation.</li>
        </ul>

        <h3>4. Third-Party Sharing</h3>
        <p>
            We do not sell your personal data. We may share necessary metadata with:
        </p>
        <ul className="list-disc pl-5 space-y-2">
            <li><strong>NIMC:</strong> For identity verification purposes only.</li>
            <li><strong>Blockchain Network:</strong> Public keys and document hashes are publicly visible on the ledger (no personal data is on-chain).</li>
        </ul>

        <h3>5. Contact Us</h3>
        <p>
            If you have privacy concerns or wish to report a vulnerability, please email us at <strong>security@inkless.ng</strong>.
        </p>
    </div>
);
